# Generated by Django 3.0.3 on 2020-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200603_0616'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quizes_passed',
            field=models.ManyToManyField(to='quiz.Quiz'),
        ),
    ]
