# Generated by Django 3.0.3 on 2020-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classroom',
            field=models.ManyToManyField(blank=True, to='classroom.Classroom'),
        ),
    ]
