# Generated by Django 3.0.3 on 2020-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_display_name',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=10),
        ),
    ]
