# Generated by Django 3.0.3 on 2020-06-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200603_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcimage',
            name='image_locaction',
        ),
        migrations.AddField(
            model_name='mcimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
